language: php

php:
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.6
      env: COVERAGE=1

before_script:
  - wget --no-check-certificate https://github.com/tideways/php-xhprof-extension/archive/v4.1.7.tar.gz && tar zxvf v4.1.7.tar.gz
  - cd php-xhprof-extension-4.1.7 && phpize && ./configure && make && make install && cd ..
  - echo "extension=tideways.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "tideways.auto_prepend_library=0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - composer install --prefer-dist --dev --ignore-platform-reqs 
  - chmod -R 0777 cache/

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      phpunit
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests with code-coverage";
      phpunit --coverage-clover=unittest-coverage.clover
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
    fi