name: Tests

on: [push]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ignore-platform-reqs"

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

  steps:
      - name: Install tideways
        run: |
		  wget --no-check-certificate https://github.com/tideways/php-xhprof-extension/archive/v4.1.7.tar.gz && tar zxvf v4.1.7.tar.gz
		  cd php-xhprof-extension-4.1.7 && phpize && ./configure && make && make install && cd ..
		  echo "extension=tideways.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
		  phpenv rehash
      - name: Install dependencies
        run: composer install $DEFAULT_COMPOSER_FLAGS
      - name: PHP Unit tests
        run: vendor/bin/phpunit
